<?php
    include("model/store.php");
    include("model/identityprovider.php");
    include("model/user.php");
    include("model/adaclass.php");
    include("model/property.php");
    include("model/grantedright.php");
    include("model/right.php");
    include("model/addon.php");
    include("model/adaobject.php");
    include("model/content.php");
    include("json.php");
?>